### ISSUE TITLE
Broken Link to 

### ISSUE THREAD

**Issue by humnit** [Whiteblock/cli#32]
**Describe the bug**
When trying to download Whiteblock CLI stable build error appears

**To Reproduce**
1. Go to 'https://github.com/Whiteblock/cli/blob/dev/README.md'
2. Section 'Latest Stable Build (amd64)'
3. Click on ' https://storage.cloud.google.com/genesis-public/cli/master/bin/macos/amd64/whiteblock'
4. See error 'No such object: genesis-public/cli/master/bin/macos/amd64/whiteblock'

**Expected behavior**
The link should redirect to the binary file for download

**Desktop (please complete the following information):**
 - OS: [macOS 10.15.1]
 - Browser [Brace 1.0]

**Comment by n8wb** [comment]
I removed the broken link, thank you very much for taking the time to let us know!
